### ISSUE TITLE
support benchmarks

### ISSUE THREAD

**Issue by brenol** [omeid/conex#1]
Just noticed conex only accepts a *testing.T as option. Perhaps it should also accept *testing.B's so containers can be used to benchmark?

Thanks

**Comment by omeid** [comment]
Hi @brenol,

I have added support for benchmarks, if 787e7a4 doesn't address your requirements, please feel free to open another issue.

Cheers.

**Comment by brenol** [comment]
hello @omeid 
great, thank you!
