### ISSUE TITLE
local or private docker images?

### ISSUE THREAD

**Issue by matthewmueller** [omeid/conex#3]
I was wondering if it's possible to create boxes from local docker images or docker images that aren't on dockerhub?

**Comment by matthewmueller** [comment]
Just found it:

```go
func init() {
	conex.PullImages = false
	conex.Require(func() string { return Image })
}
```

Not sure about private images, but I needed local images more. This library is awesome!

**Comment by omeid** [comment]
Thanks for the kind words!

Support for private registry is coming soon. :)
