### ISSUE TITLE
What does address point to?

### ISSUE THREAD

**Issue by matthewmueller** [omeid/conex#5]
I'm not sure if this is a bug or a network configuration issue on my end, but during local development, `container.Address()` points to something like: `172.17.0.3`, when it should really output `127.0.0.1`.

I'm guessing it makes more sense in the context of a CI, but would be great to also be able to use `container.Address()` locally.

I'm running docker for OSX.

**Comment by omeid** [comment]
`container.Address()` points to the docker containers IP address. If you're using docker for OSx, I don't believe it will be directly accessible from your host because the docker instance runs inside a virtual machine. Hope this addresses your question.

**Comment by omeid** [comment]
Yeah, just checked and the state of Docker for Mac is still the same. Perhaps a link to official docker docs on [Docker for Mac Networking](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds) is a good idea.

**Comment by matthewmueller** [comment]
Ah interesting, I wonder if this could be a workaround: `docker.for.mac.localhost` (not an expert in this area)

**Comment by omeid** [comment]
I am sorry but adding support for Docker for X would complicate things. If you found a simpler way for supporting docker for mac and the like, please feel free to reopen this issue.

**Comment by omeid** [comment]
Docker for Mac and friends are now supported with #7.
